# This workflow will build a golang project and generate the executable binary file
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o sid

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sid
        path: ./sid
